name: cr-asst-action
description: An action powered by cr-asst that reviews your pull requests with AI assistants.
author: mys1024

branding:
  icon: code
  color: blue

runs:
  using: node20
  main: dist/index.js

inputs:
  github-token:
    description: Github token.
    required: true
  model:
    description: AI Model to use for review.
    required: true
  provider:
    description: 'AI service provider (options: "openai", "deepseek", "xai", "anthropic", "google"). (default: "openai")'
    required: false
  base-url:
    description: Base URL for the AI service API.
    required: false
  api-key:
    description: API key for the AI service.
    required: true
  include:
    description: Files and directories to include in review, separated by commas.
    required: false
  exclude:
    description: Files and directories to exclude from review, separated by commas.
    required: false
  prompt-file:
    description: 'Path to a custom prompt file, or a builtin prompt (options: "en" or "zh-cn"). (default: "en")'
    required: false
  system-prompt-file:
    description: Path to a custom system prompt file.
    required: false
  disable-tools:
    description: Whether to disable tools.
    required: false
  max-steps:
    description: Maximum number of AI model calls.
    required: false
  temperature:
    description: Temperature for the AI model.
    required: false
  top-p:
    description: Top P for the AI model.
    required: false
  top-k:
    description: Top K for the AI model.
    required: false
  output-file:
    description: Path to a file to save review result.
    required: false
