name: cr-asst-action
description: An action powered by cr-asst that reviews your pull requests with AI assistants.
author: mys1024

branding:
  icon: heart
  color: red

runs:
  using: node20
  main: dist/index.mjs

inputs:
  github-token:
    description: Github token.
    required: true
  model:
    description: AI Model to use for review.
    required: true
  api-key:
    description: API key for the AI service.
    required: true
  base-url:
    description: Base URL for the AI service API.
    required: false
  prompt-file:
    description: Path to a custom prompt file, or a builtin prompt ("en", "zh-cn", or "zh-cn-nyan").
    required: false
  diffs-cmd:
    description: Command to get code diffs for review.
    required: false
  input-price:
    description: Price per million input tokens. For computing cost.
    required: false
  output-price:
    description: Price per million output tokens. For computing cost.
    required: false
